### ISSUE TITLE
An adapter must be provided

### ISSUE THREAD

**Issue by simpsss** [lacaulac/rcon-web-admin#19]
/root/rcon-web-admin/node_modules/lowdb/lib/main.js:8
    throw new Error('An adapter must be provided, see https://github.com/typicode/lowdb/#usage');
    ^

Error: An adapter must be provided, see https://github.com/typicode/lowdb/#usage
    at module.exports (/root/rcon-web-admin/node_modules/lowdb/lib/main.js:8:11)
    at Object.db.get (/root/rcon-web-admin/src/db.js:35:16)
    at Function.RconServer.connectAll (/root/rcon-web-admin/src/rconserver.js:185:22)
    at Object.<anonymous> (/root/rcon-web-admin/src/rconserver.js:215:12)

**Comment by abakisensoy** [comment]
I having the same problem.

**Comment by chylex** [comment]
Not sure what's going on, but I fixed it in my branch https://github.com/chylex/Minecraft-RCON-Web-Admin/commit/463ad4b49b515d0c4cc9e0b75a0ecb1d60ec3b22
